### ISSUE TITLE
language models

### ISSUE THREAD

**Issue by jmsellier** [cnap/sentence-compression#2]
I am trying to run this code by following the example reported in the manual (README file):

> java -Xms2g -Xmx10g -Djava.library.path=$ILOG -cp bin:lib/berkeleylm.jar:lib/cplex.jar:lib/stanford-parser.jar research.compression.SentenceCompressor -in=data/sample_text -lm=gigaword.kn3.gz

Where can I find the language model file "gigaword.kn3.gz" mentioned in the above command?

Thanks!

**Comment by cnap** [comment]
We cannot release our language model for licensing reasons, but you can use any ARPA format trigram language model in place of gigaword.kn3.gz. One source to download language models from is http://www.keithv.com/software/giga/ (note that I haven't used these models myself but others have told me that they work).

**Comment by jmsellier** [comment]
I tried every single language model at that link and, unfortunately, I always got the same error:

Loading parser from serialized file /home/sellier/sentence-compression-master/bin/research/lib/englishPCFG.ser.gz ... done [1.2 sec].
1 sents loaded
Loading language model from ./kenlm.tar.gz
Error: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1911)
    at edu.berkeley.nlp.lm.io.ArpaLmReader.parseLine(ArpaLmReader.java:170)
    at edu.berkeley.nlp.lm.io.ArpaLmReader.parseNGrams(ArpaLmReader.java:146)
    at edu.berkeley.nlp.lm.io.ArpaLmReader.parse(ArpaLmReader.java:78)
    at edu.berkeley.nlp.lm.io.ArpaLmReader.parse(ArpaLmReader.java:18)
    at edu.berkeley.nlp.lm.io.LmReaders.firstPassCommon(LmReaders.java:522)
    at edu.berkeley.nlp.lm.io.LmReaders.firstPassArpa(LmReaders.java:499)
    at edu.berkeley.nlp.lm.io.LmReaders.readArrayEncodedLmFromArpa(LmReaders.java:168)
    at edu.berkeley.nlp.lm.io.LmReaders.readArrayEncodedLmFromArpa(LmReaders.java:148)
    at edu.berkeley.nlp.lm.io.LmReaders.readArrayEncodedLmFromArpa(LmReaders.java:143)
    at research.lib.MyBerkeleyLm.readLmFromFile(Unknown Source)
    at research.lib.MyBerkeleyLm.<init>(Unknown Source)
    at research.compression.SentenceCompressor.initialize(Unknown Source)
    at research.compression.SentenceCompressor.main(Unknown Source)

What am I doing wrong? Any hint? MANY thanks!
