### ISSUE TITLE
String index out of range: -1

### ISSUE THREAD

**Issue by jmsellier** [cnap/sentence-compression#3]
Hello,

I have been able to compile the code and run the "compress" script. I also downloaded a language model from (as it seems to do not be provided in this package):

http://cmusphinx.sourceforge.net/wiki/download

When I type in a terminal:

> ./compress -i ./sample_sentence.txt -l ./cmusphinx-5.0-en-us.lm

I get the following error:

java -Xmx1g -Djava.library.path= -classpath ./bin:./lib/stanford-parser.jar:./lib/berkeleylm.jar:/opt/ibm/ILOG/CPLEX_Studio_Community1262/cplex/lib/cplex.jar research.compression.SentenceCompressor -in=./sample_sentence.txt -lm=./cmusphinx-5.0-en-us.lm
Loading parser from serialized file /home/sellier/pippo/sentence-compression-master/bin/research/lib/englishPCFG.ser.gz ... done [1.2 sec].
1 sents loaded
Loading language model from ./cmusphinx-5.0-en-us.lm
Error: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1911)
    at edu.berkeley.nlp.lm.io.ArpaLmReader.parseLine(ArpaLmReader.java:170)
    at edu.berkeley.nlp.lm.io.ArpaLmReader.parseNGrams(ArpaLmReader.java:146)
    at edu.berkeley.nlp.lm.io.ArpaLmReader.parse(ArpaLmReader.java:78)
    at edu.berkeley.nlp.lm.io.ArpaLmReader.parse(ArpaLmReader.java:18)
    at edu.berkeley.nlp.lm.io.LmReaders.firstPassCommon(LmReaders.java:522)
    at edu.berkeley.nlp.lm.io.LmReaders.firstPassArpa(LmReaders.java:499)
    at edu.berkeley.nlp.lm.io.LmReaders.readArrayEncodedLmFromArpa(LmReaders.java:168)
    at edu.berkeley.nlp.lm.io.LmReaders.readArrayEncodedLmFromArpa(LmReaders.java:148)
    at edu.berkeley.nlp.lm.io.LmReaders.readArrayEncodedLmFromArpa(LmReaders.java:143)
    at research.lib.MyBerkeleyLm.readLmFromFile(Unknown Source)
    at research.lib.MyBerkeleyLm.<init>(Unknown Source)
    at research.compression.SentenceCompressor.initialize(Unknown Source)
    at research.compression.SentenceCompressor.main(Unknown Source)

Can someone help me to fix this problem? Am I doing something wrong?

Many thanks in advance!

**Comment by cnap** [comment]
This issue has been addressed with the fix_spacing.pl script.
