### ISSUE TITLE
Exception: ilog/concert/IloException

### ISSUE THREAD

**Issue by catherine667** [cnap/sentence-compression#4]
Hi,
          I used cmusphinx-5.0-en-us.lm as a language model. Hopefully it can work too. I also download IBM ILOG CPLEX Optimization Studio 12.6.3 (the newest version). When I run my program, I have the following error:
 ./compress -i ./sample_sentence.txt -l cmusphinx-5.0-en-us_fixed.lm
java -Xmx10g -Djava.library.path=$/Users/liqun/Applications/IBM/ILOG/CPLEX_Studio_Community1263/cplex/bin/x86-64_osx/ -classpath ./bin:./lib/stanford-parser.jar:./lib/berkeleylm.jar:$/Users/liqun/Applications/IBM/ILOG/CPLEX_Studio_Community1263/cplex/lib/cplex.jar research.compression.SentenceCompressor -in=./sample_sentence.txt -lm=cmusphinx-5.0-en-us_fixed.lm
Loading parser from serialized file /Users/liqun/Documents/workspace/LM/bin/research/lib/englishPCFG.ser.gz ... done [1.1 sec].
1 sents loaded
Loading language model from cmusphinx-5.0-en-us_fixed.lm
Exception in thread "main" java.lang.NoClassDefFoundError: ilog/concert/IloException
    at research.compression.SentenceCompressor.initialize(SentenceCompressor.java:139)
    at research.compression.SentenceCompressor.main(SentenceCompressor.java:58)
Caused by: java.lang.ClassNotFoundException: ilog.concert.IloException
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 2 more
         I have tried to fix these bugs for a long time. Could you please give some suggestions on how to fix these bugs? By the way, I am using the trial version. Do I need to buy the full production? Also, could you tell me which version of cplex you have used?
         Thank you again! This would be so helpful for my research.

**Comment by wangliangguo** [comment]
with the same issue, have you solve it?
I finally found the reason is the cplex path  should be correctly set in compress file.
